from Message import Message

m1 = Message("Pasquale", "Bryan")
print(m1.sender)
print(m1.receiver)
m1.insertObjectOfMessage()
print("Inserted Object:", m1.objectOfMessage)
print("\nBodyOfMessage:")
m1.insertBodyOfMessage()
print("Body of message:", m1.bodyOfMessage)
m1.confidentialMessage(confidentiality=1)
print("Level of confidentiality:", m1.confidentiality)
m1.cypherCaesar()
print("\nNumber of consonants in 'object of message':", m1.counterConsonants, "--------> ", m1.objectOfMessage)
print("Encrypted message:", m1.encryptedMessage)
m1.decipherCaesar()
print("Decrypted Message:", m1.decryptedMessage)
m1.append_greetings()
print(m1.bodyOfMessage)
m1.to_fullText()
print(f"\nTransformed message:\n{m1.transformedMessage}")
print("\nPrintatura dell'oggetto:")
print(m1)
